---
openapi: 3.0.2
info:
  title: Camel K Object API
  version: 1.0.0
  description: A CRUD API for create messa in kafka
paths:
  /:
    get:
      responses:
        "200":
          description: teste
      operationId: Running
    post:
      requestBody:
        description: "{\n    \"message\": \"Hello Word!\"\n}"
        content:
          application/json:
            examples:
              message:
                value:
                  message: Hello Word!
      responses:
        "200":
          description: testando
      operationId: SendMessage