apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rabbit-mq-message
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbit-mq-message
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75