apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - host: backend.tcc-pucminas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
  - host: frontend.tcc-pucminas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: viewmap.tcc-pucminas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: viewmap-service
            port:
              number: 80
  - host: rabbit.tcc-pucminas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: definition
            port:
              number: 15672
  - host: integracao.tcc-pucminas.com
    http:
      paths:
      - path: /rabbit
        pathType: Prefix
        backend:
          service:
            name: rabbit-mq-message
            port:
              number: 80
      - path: /servicos/iptu
        pathType: Prefix
        backend:
          service:
            name: servicos  
            port:
              number: 80
      - path: /servicos/stur
        pathType: Prefix
        backend:
          service:
            name: stur
            port:
              number: 80
  - host: mock.tcc-pucminas.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: castlemock-service
            port:
              number: 80
      