kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          root /var/www;

          index /public/index.php;
          error_log  /var/log/nginx/error.log;
          access_log /var/log/nginx/access.log;
          
          location / {
              try_files $uri $uri/ /public/index.php?$query_string;
          }
          
          location ~ \.php$ {
              fastcgi_pass localhost:9000;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;
          }
        }
