apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-teste
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-teste
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75