---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-teste
  template:
    metadata:
      labels:
        app: backend-teste
    spec:
      containers:
      - name: backend-teste
        image: jheffh2012/cluster-fpm:latest
        ports:
        - containerPort: 9000
          name: fastcgi
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: ws-backend-teste
        image: jheffh2012/cluster-nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
