apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-storage-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/www/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi