---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: backend-service
  # namespace: integracao
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: backend-port
    targetPort: 80
  selector:
    app: backend-teste