apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: servicos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicos
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75