apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stur
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stur
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75