apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: viewmap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: viewmap
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75