kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-front
data:
  default.conf: |
        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          root /usr/share/nginx/html/;

          error_log  /var/log/nginx/error.log;
          access_log /var/log/nginx/access.log;
          
          location / {
            index index.html index.htm;
            try_files $uri $uri/ /index.html =404;
          }
        }
