---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: frontend-port
    targetPort: 80
  selector:
    app: frontend